"""
Step 4.5 of the final practical brief: an index of every workbook, figure,
chapter and handback produced in Weeks 1-7, built from the file system (so
it can never list a file that does not exist), for assembling the final
thesis document.

Usage: PYTHONPATH=. python scripts/build_deliverables_index.py
Writes thesis_docs/DELIVERABLES_INDEX.md.
"""
import glob
import os
import re

OUT = "thesis_docs/DELIVERABLES_INDEX.md"


def week_of(name):
    m = re.search(r"week(\d+)", name.lower())
    if m:
        return f"Week {m.group(1)}"
    if name.startswith("economics_cop"):
        return "Week 5"
    return "Weeks 2-4 (pre-Week-5 naming)"


def caption_title(png):
    cap = png.replace(".png", ".caption.md")
    if not os.path.exists(cap):
        return ""
    lines = [l.strip() for l in open(cap, encoding="utf-8") if l.strip() and not l.startswith("#")]
    return lines[0][:160] + ("..." if lines and len(lines[0]) > 160 else "") if lines else ""


def main():
    out = ["# Deliverables Index — Weeks 1–7", "",
           "Generated by `scripts/build_deliverables_index.py` from the files present in the repository.",
           "Paths are relative to the repository root.", ""]
    out += ["## Chapters (`thesis_docs/chapters/`)", "", "| File | Title |", "|---|---|"]
    for p in sorted(glob.glob("thesis_docs/chapters/*.md")):
        first = next((l.strip("# \n") for l in open(p, encoding="utf-8") if l.startswith("# ")), "")
        out.append(f"| `{p}` | {first} |")
    out += ["", "## Weekly handbacks and progress log (`thesis_docs/`)", "", "| File |", "|---|"]
    for p in sorted(glob.glob("thesis_docs/*.docx") + glob.glob("thesis_docs/Week*.md") + ["thesis_docs/overnight_report.md"]):
        if os.path.exists(p):
            out.append(f"| `{p}` |")
    out += ["", "## Excel workbooks", "", "| Week | File |", "|---|---|"]
    books = sorted(glob.glob("results/*.xlsx") + glob.glob("experiments/*/results/*.xlsx")
                   + glob.glob("experiments/*/results/*/*.xlsx"))
    for p in sorted(books, key=lambda p: (week_of(os.path.basename(p)), p)):
        out.append(f"| {week_of(os.path.basename(p))} | `{p}` |")
    out += ["", "## Figures (`figures/`, each with `.pdf` and `.caption.md`)", "", "| File | What it shows (caption, first line) |", "|---|---|"]
    for p in sorted(glob.glob("figures/*.png")):
        out.append(f"| `{p}` | {caption_title(p).replace('|', '/')} |")
    out += ["", "## Sources", "", "| File |", "|---|"]
    for p in sorted(glob.glob("thesis_docs/sources/*.md") + glob.glob("thesis_docs/references/*.md")):
        out.append(f"| `{p}` |")
    with open(OUT, "w", encoding="utf-8") as f:
        f.write("\n".join(out).replace(os.sep, "/") + "\n")  # forward slashes on Windows too
    print(f"Wrote {OUT}: {len(books)} workbooks, {len(glob.glob('figures/*.png'))} figures")


if __name__ == "__main__":
    main()
