"""
Week 5, Gate 3/Gate 4: one-time schema migration for results/master_results.csv.

Adds four new columns (day_type, scenario_id, analysis_row, superseded) to
every existing row. Does NOT touch any STATS_COLUMNS value -- this is a
metadata migration, not a data mutation, and it runs exactly once.

Every row that exists before this migration was produced before the Gate 4
fix to ev2gym/utilities/utils.py::generate_power_setpoints (the live
ENTSO-E price dependency inside the control layer) -- so every existing
row, across every config (not just station_v0_bogota), is marked
superseded=True, analysis_row=False. This is a deliberate widening beyond
the literal "552 station_v0_bogota rows" instruction: the other ~401 rows
(station_n02_tx100 etc., the smoke test) were generated by the identical
buggy function and are equally stale, so leaving them unmarked would be
inconsistent with the same finding. Flagged explicitly, not applied
silently.

Usage:
    PYTHONPATH=. python scripts/migrate_registry_schema_week5.py
"""
import pandas as pd

from ev2gym_thesis.registry import REGISTRY_PATH, REGISTRY_COLUMNS
from ev2gym_thesis.eval_protocol import day_type


def main():
    df = pd.read_csv(REGISTRY_PATH, dtype=str, keep_default_na=False)
    n_before = len(df)
    print(f"Loaded {n_before} existing rows from {REGISTRY_PATH}")

    already_migrated = {"day_type", "scenario_id", "analysis_row", "superseded"} <= set(df.columns)
    if already_migrated:
        print("Registry already has the Week 5 schema columns -- nothing to do.")
        return

    def classify(eval_day_str):
        y, m, d = (int(x) for x in eval_day_str.split("-"))
        return day_type((y, m, d))

    df["day_type"] = df["eval_day"].apply(classify)
    df["scenario_id"] = df["seed"].astype(str) + "_" + df["day_type"]
    df["analysis_row"] = "False"
    df["superseded"] = "True"

    missing = set(REGISTRY_COLUMNS) - set(df.columns)
    extra = set(df.columns) - set(REGISTRY_COLUMNS)
    assert not missing, f"Migration incomplete, still missing: {missing}"
    assert not extra, f"Unexpected extra columns after migration: {extra}"

    df = df[REGISTRY_COLUMNS]
    df.to_csv(REGISTRY_PATH, index=False)

    print(f"Migrated {len(df)} rows (unchanged count: {len(df) == n_before}).")
    print(f"All {len(df)} rows marked superseded=True, analysis_row=False.")
    print(df["day_type"].value_counts().to_string())


if __name__ == "__main__":
    main()
